# Generated by Django 4.2.1 on 2023-06-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='talks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('speaker', models.CharField(max_length=40)),
                ('linkedin_profile', models.URLField()),
                ('github_profile', models.URLField()),
            ],
        ),
    ]
