# Generated by Django 4.2.1 on 2023-06-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talks',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
