# Generated by Django 4.2.1 on 2023-06-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_talks_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='talks',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
    ]
